[package]
name = "apc"
version = "0.1.0"
edition = "2021"


[dependencies]
rand = "0.8.0"
lib1 = { path = "../lib1" }
actix-web = "3"
serde = "1.0.135"
futures = "0.3.15"
serde_json = "1.0.79"
json = "0.12.4"
env_logger = "0.9.0"